### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by FragozoLeonardo** [buruzaemon/natto#78]
Hello, first off, thank you for building this gem.

I have a few questions regarding the gem and MeCab processing.

My friend and I are translating a portion of around 100,000 words from Edict to our language, and we plan to create a mini-dictionary for our website. I would like to incorporate a sentence analyzer using MeCab, but instead of the regular MeCab annotations, I want to replace them with our translated words. For example:

火星 - "Marte (planeta)" は (partícula de tópico) 赤い (vermelho) です (auxiliar de polidez).

I would like to know if it's possible to achieve this using newer versions of Ruby.

Again, thank you in advance.

**Comment by buruzaemon** [comment]
Hello, @FragozoLeonardo, and thank you for reaching out to me.

First of all, please let me apologize for not responding any sooner. I am not actively supporting this project anymore, and I rarely check my notifications.

About your question, which version of Ruby you use should not matter. natto is essentially a wrapper around a MeCab installation, and it sounds like you are more interested in hacking the dictionary being used by MeCab. 

Being that MeCab is intended as a part-of-speech / morpheme analyzer, I do not think it will work well as in supporting translations per your idea. If you can read Japanese, then you might find some ideas on the [MeCab Users Mailing List](https://lists.osdn.me/mailman/listinfo/mecab-users), but that list is pretty dated by this point since MeCab itself has not been actively supported for many years now. MeCab is extremely flexible and configurable, but I think your idea is beyond its intended usage.

**Comment by FragozoLeonardo** [comment]
Well, I can read Japanese to a extent, I'm like N3 and improving, but thank you for your reply, the project ended dying out because my colleague gave up on Japanese, and now it's just me studying it, thank you again for your kind reply.
